services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_HOST_PORT}:5432
  cache:
    image: 'redis:latest'
    restart: 'always'
    ports:
      - ${REDIS_HOST_PORT}:6379