"""user-document relationship

Revision ID: acd518686909
Revises: 5878817b2e0c
Create Date: 2025-02-13 13:45:42.091930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = 'acd518686909'
down_revision: Union[str, None] = '5878817b2e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    # ### end Alembic commands ###
